/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotableProjectsRouteImport } from './routes/notable-projects'
import { Route as IndexRouteImport } from './routes/index'

const NotableProjectsRoute = NotableProjectsRouteImport.update({
  id: '/notable-projects',
  path: '/notable-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notable-projects': typeof NotableProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notable-projects': typeof NotableProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notable-projects': typeof NotableProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notable-projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notable-projects'
  id: '__root__' | '/' | '/notable-projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotableProjectsRoute: typeof NotableProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notable-projects': {
      id: '/notable-projects'
      path: '/notable-projects'
      fullPath: '/notable-projects'
      preLoaderRoute: typeof NotableProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotableProjectsRoute: NotableProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
